# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validate pull requests

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yaml check
        id: YamlCheck
        shell: bash
        run: |
          echo START
          git fetch origin main --depth=1
          git branch --show-current
          git --no-pager diff --unified=0 origin/main -- contributions_list.yaml | grep '^+  -' | while read args;do echo $args | awk '{if ($3 ==""){print $0,"=>","Not valid entry"; exit 1;}else{print $3}}'| echo -;echo "::set-output name=YamlCheck::strawberry"; done
          echo "::set-output name=YamlCheck::Farid"
          echo END
      - name: check Resault
        run: echo join(steps.YamlCheck.outputs.*, '\n')
